'use client';

import { ProductInfo, ExtractedFrame, SegmentedImage, EnhancedImage } from '@/lib/types';

interface ProductCardProps {
  product: ProductInfo;
  frame?: ExtractedFrame;
  segmented?: SegmentedImage;
  enhanced: EnhancedImage[];
}

export default function ProductCard({ product, frame, segmented, enhanced }: ProductCardProps) {
  return (
    <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
      <div className="p-6 border-b border-gray-200 dark:border-gray-700">
        <h3 className="text-xl font-bold text-gray-800 dark:text-white mb-2">
          {product.name}
        </h3>
        <p className="text-gray-600 dark:text-gray-300 text-sm mb-2">
          {product.description}
        </p>
        <div className="flex items-center space-x-2">
          <span className="text-xs font-medium text-gray-500 dark:text-gray-400">
            Confidence:
          </span>
          <div className="flex-1 bg-gray-200 dark:bg-gray-700 rounded-full h-2 max-w-xs">
            <div
              className="bg-green-500 h-2 rounded-full"
              style={{ width: `${product.confidence}%` }}
            ></div>
          </div>
          <span className="text-xs font-semibold text-gray-700 dark:text-gray-300">
            {product.confidence}%
          </span>
        </div>
      </div>

      {/* Extracted Frame */}
      {frame && (
        <div className="p-6 border-b border-gray-200 dark:border-gray-700">
          <h4 className="text-lg font-semibold text-gray-800 dark:text-white mb-3">
            Extracted Frame
          </h4>
          <div className="mb-3">
            <img
              src={`data:image/jpeg;base64,${frame.frameBase64}`}
              alt={`${product.name} frame`}
              className="w-full rounded-lg"
            />
          </div>
          <div className="text-sm text-gray-600 dark:text-gray-400">
            <p><strong>Timestamp:</strong> {frame.frameTimestamp}s</p>
            <p><strong>Reason:</strong> {frame.reason}</p>
          </div>
        </div>
      )}

      {/* Segmented Image */}
      {segmented && (
        <div className="p-6 border-b border-gray-200 dark:border-gray-700">
          <h4 className="text-lg font-semibold text-gray-800 dark:text-white mb-3">
            Segmented Product
          </h4>
          <img
            src={`data:image/jpeg;base64,${segmented.segmentedBase64}`}
            alt={`${product.name} segmented`}
            className="w-full rounded-lg"
          />
        </div>
      )}

      {/* AI-Generated Enhanced Images */}
      {enhanced.length > 0 && (
        <div className="p-6 bg-gradient-to-br from-blue-50 to-purple-50 dark:from-gray-700 dark:to-gray-800">
          <div className="flex items-center mb-4">
            <h4 className="text-lg font-semibold text-gray-800 dark:text-white">
              ✨ AI-Enhanced Product Shots
            </h4>
            <span className="ml-2 px-2 py-1 text-xs font-semibold bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-200 rounded-full">
              Gemini 2.5
            </span>
          </div>
          <p className="text-xs text-gray-600 dark:text-gray-400 mb-4">
            Professional product photographs generated by Gemini AI
          </p>
          <div className="space-y-4">
            {enhanced.map((img, idx) => (
              <div key={idx} className="bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-lg p-4 shadow-md">
                <div className="mb-3">
                  <img
                    src={`data:image/jpeg;base64,${img.enhancedBase64}`}
                    alt={`${product.name} ${img.style}`}
                    className="w-full rounded-lg shadow-lg hover:shadow-xl transition-shadow duration-300"
                  />
                </div>
                <div className="flex items-start justify-between">
                  <div className="flex-1">
                    <p className="text-sm font-semibold text-gray-800 dark:text-gray-200 mb-1 capitalize">
                      📸 {img.style}
                    </p>
                    <p className="text-xs text-gray-600 dark:text-gray-400 line-clamp-2">
                      {img.description}
                    </p>
                  </div>
                  <button className="ml-2 px-3 py-1 text-xs font-medium bg-blue-500 hover:bg-blue-600 text-white rounded-md transition-colors duration-200">
                    Download
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
